import { spawn } from "node:child_process";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import type { FieldsData } from "@kenjiuno/msgreader";
import MsgReader from "@kenjiuno/msgreader";
import { type ParsedMail, simpleParser } from "mailparser";
import { db, withSqliteBusyRetry } from "./db";
import { PRIVILEGED_KEYWORDS_RE } from "./exclusions";

interface AnalysisMetrics {
  uniqueCount: number;
  duplicateCount: number;
  totalProcessed: number;
  totalAttachments: number;
}

// Smarter Fallback Generator for emails without standard Message-IDs
function generateFallbackHash(
  senderRaw: string,
  subjectRaw: string,
  bodyRaw: string,
): string {
  const sender = (senderRaw || "").toLowerCase().replace(/[^a-z0-9]/g, "");
  const subject = (subjectRaw || "")
    .toLowerCase()
    .replace(/^(re|fw|fwd|wg|aw)\s*:\s*/g, "")
    .replace(/[^a-z0-9]/g, "");
  const body = (bodyRaw || "")
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "")
    .substring(20, 120);

  return crypto
    .createHash("sha256")
    .update(`${sender}_${subject}_${body}`)
    .digest("hex");
}

export async function scanFileMetadata(fileId: string): Promise<void> {
  // 🚀 ARCHITECTURE UPGRADE:
  // readpst does not support scanning without extracting.
  // We instantly advance the file to pending_analysis so the UI orchestrator moves directly to Phase 2.
  await withSqliteBusyRetry(
    () =>
      db
        .prepare(`
    UPDATE processed_files 
    SET total_emails = 0, total_attachments = 0, status = 'pending_analysis'
    WHERE id = ?
  `)
        .run(fileId),
    "scanFileMetadata update",
  );
}

// Helper to recursively collect all EMLs generated by readpst
async function getEmlFiles(
  dir: string,
  fileList: string[] = [],
): Promise<string[]> {
  if (!fs.existsSync(dir)) return fileList;
  const files = await fs.promises.readdir(dir, { withFileTypes: true });
  for (const file of files) {
    const fullPath = path.join(dir, file.name);
    if (file.isDirectory()) {
      await getEmlFiles(fullPath, fileList);
    } else if (file.name.toLowerCase().endsWith(".eml")) {
      fileList.push(fullPath);
    }
  }
  return fileList;
}

export async function analyzePstDuplicates(
  fileId: string,
  outputBaseDir = process.env.EXTRACTED_PATH ||
    "/Users/rgomes/Projects/extracted_emails",
) {
  const row = db
    .prepare("SELECT filepath FROM processed_files WHERE id = ?")
    .get(fileId) as { filepath: string } | undefined;
  if (!row) throw new Error("File metadata not found.");

  await withSqliteBusyRetry(
    () =>
      db
        .prepare(
          "UPDATE processed_files SET status = 'processing' WHERE id = ?",
        )
        .run(fileId),
    "mark processing",
  );
  await withSqliteBusyRetry(
    () => db.prepare("DELETE FROM emails WHERE file_id = ?").run(fileId),
    "clear prior emails",
  );

  const stagingPath =
    process.env.STAGING_PATH || "/Users/rgomes/Projects/staging-area";

  let cleanRelativePath = "";
  if (row.filepath.startsWith(stagingPath)) {
    const rel = path.relative(stagingPath, row.filepath);
    cleanRelativePath = path.dirname(rel);
  } else {
    cleanRelativePath = fileId;
  }

  if (cleanRelativePath === "." || cleanRelativePath === "") {
    cleanRelativePath = path.parse(row.filepath).name;
  }

  const pstExtractionKey = crypto
    .createHash("sha256")
    .update(`${fileId}:${row.filepath}`)
    .digest("hex")
    .substring(0, 12);

  const caseFolder = path.join(outputBaseDir, cleanRelativePath);
  if (!fs.existsSync(caseFolder)) fs.mkdirSync(caseFolder, { recursive: true });

  // Per-PST hidden folder for raw extracted EMLs before normalization
  const targetFolder = path.join(caseFolder, `.pst-eml-${pstExtractionKey}`);
  if (!fs.existsSync(targetFolder))
    fs.mkdirSync(targetFolder, { recursive: true });

  // The temporary extraction sandbox
  const tempDir = path.join(outputBaseDir, `.tmp_extract_${fileId}`);
  if (fs.existsSync(tempDir))
    fs.rmSync(tempDir, { recursive: true, force: true });
  fs.mkdirSync(tempDir, { recursive: true });

  const metrics: AnalysisMetrics = {
    uniqueCount: 0,
    duplicateCount: 0,
    totalProcessed: 0,
    totalAttachments: 0,
  };

  // ==========================================
  // PHASE 1: Brute-Force Extraction (libpst)
  // ==========================================
  // Fail fast with a clear message if the source PST no longer exists on disk
  // (e.g. a stale DB row left behind after the staging layout was reorganized).
  if (!fs.existsSync(row.filepath)) {
    throw new Error(
      `Source PST not found on disk: ${row.filepath}. The staging file was likely moved or deleted, leaving a stale record. Re-sync the staging area (and reset/remove this case) before retrying.`,
    );
  }

  console.log(`[Analyzer] Spawning readpst for file ${fileId}...`);
  await new Promise<void>((resolve, reject) => {
    // -r = Recursive folder extraction, -e = Output as standard .eml, -o = Target directory
    const child = spawn("readpst", ["-r", "-e", "-o", tempDir, row.filepath]);

    let stderr = "";
    child.stderr?.on("data", (chunk) => {
      stderr += chunk.toString();
    });

    child.on("error", (err) => {
      reject(
        new Error(
          `Failed to start readpst. Is libpst installed on the system? Error: ${err.message}`,
        ),
      );
    });

    child.on("close", (code) => {
      if (code === 0) {
        resolve();
      } else {
        const detail = stderr.trim();
        reject(
          new Error(
            `readpst failed with exit code ${code} for ${row.filepath}${
              detail ? `: ${detail}` : ""
            }`,
          ),
        );
      }
    });
  });

  console.log(
    `[Analyzer] readpst complete. Scanning temp directory for EMLs...`,
  );

  // ==========================================
  // PHASE 2: Flatten & Deduplicate
  // ==========================================
  const emlFiles = await getEmlFiles(tempDir);

  const checkStmt = db.prepare(
    "SELECT id FROM emails WHERE email_hash = ? LIMIT 1",
  );
  const insertStmt = db.prepare(`
    INSERT INTO emails (id, file_id, message_id, sent_date, email_hash, is_duplicate, parent_email_hash, is_attachment)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
  `);

  function msgDataToEml(data: {
    headers?: string;
    senderEmail?: string;
    senderName?: string;
    recipients?: Array<{ email?: string; name?: string }>;
    subject?: string;
    messageDeliveryTime?: string;
    clientSubmitTime?: string;
    creationTime?: string;
    body?: string;
  }): string {
    const normalizedHeaders = (data.headers || "").trim();
    if (
      /^from:/im.test(normalizedHeaders) &&
      /^subject:/im.test(normalizedHeaders)
    ) {
      return `${normalizedHeaders}\n\n${data.body || ""}`;
    }

    const sender =
      data.senderEmail || data.senderName || "unknown@example.invalid";
    const recipients = (data.recipients || [])
      .map((r) => r.email || r.name || "")
      .filter(Boolean)
      .join(", ");
    const sentAt =
      data.messageDeliveryTime || data.clientSubmitTime || data.creationTime;

    const lines = [
      `From: ${sender}`,
      `To: ${recipients || "undisclosed-recipients:;"}`,
      `Subject: ${data.subject || "(no subject)"}`,
      ...(sentAt ? [`Date: ${sentAt}`] : []),
      "MIME-Version: 1.0",
      'Content-Type: text/plain; charset="utf-8"',
      "",
      data.body || "",
    ];

    return lines.join("\n");
  }

  async function processMsgFile(
    msgPath: string,
    parentHash: string | null = null,
  ): Promise<void> {
    try {
      const msgBuffer = fs.readFileSync(msgPath);
      const reader = new MsgReader(
        new DataView(
          msgBuffer.buffer,
          msgBuffer.byteOffset,
          msgBuffer.byteLength,
        ),
      );
      const msgData = reader.getFileData() as {
        headers?: string;
        senderEmail?: string;
        senderName?: string;
        recipients?: Array<{ email?: string; name?: string }>;
        subject?: string;
        messageDeliveryTime?: string;
        clientSubmitTime?: string;
        creationTime?: string;
        body?: string;
        attachments?: FieldsData[];
      };

      const synthesizedEmlPath = path.join(
        tempDir,
        `msg_${crypto.randomUUID()}.eml`,
      );
      fs.writeFileSync(synthesizedEmlPath, msgDataToEml(msgData));

      const msgEmailHash = await processEmlFile(synthesizedEmlPath, parentHash);
      const nestedParentHash = msgEmailHash || parentHash;

      if (!msgData.attachments || msgData.attachments.length === 0) return;

      metrics.totalAttachments += msgData.attachments.length;

      for (const msgAttachment of msgData.attachments) {
        let extracted:
          | { fileName?: string; content?: Uint8Array | Buffer | string }
          | undefined;

        try {
          extracted = reader.getAttachment(msgAttachment) as {
            fileName?: string;
            content?: Uint8Array | Buffer | string;
          };
        } catch (_err) {
          continue;
        }

        const content = extracted?.content;
        if (!content) continue;

        const attachmentName =
          extracted?.fileName ||
          msgAttachment.fileName ||
          msgAttachment.fileNameShort ||
          `msg_att_${crypto.randomUUID()}`;
        const attachmentExt = path.extname(attachmentName).toLowerCase();
        if (attachmentExt !== ".eml" && attachmentExt !== ".msg") continue;

        const nestedTempPath = path.join(
          tempDir,
          `nested_${crypto.randomUUID()}${attachmentExt}`,
        );

        const nestedBuffer = Buffer.isBuffer(content)
          ? content
          : typeof content === "string"
            ? Buffer.from(content)
            : Buffer.from(content);

        fs.writeFileSync(nestedTempPath, nestedBuffer);

        if (attachmentExt === ".msg") {
          await processMsgFile(nestedTempPath, nestedParentHash);
        } else {
          await processEmlFile(nestedTempPath, nestedParentHash);
        }
      }
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      console.warn(
        `[Analyzer] Failed to parse MSG file ${msgPath}: ${message}`,
      );
    }
  }

  async function processEmlFile(
    filePath: string,
    parentHash: string | null = null,
  ): Promise<string | null> {
    metrics.totalProcessed++;
    const rawEml = fs.readFileSync(filePath);

    // Biome Fix: Explicitly type as ParsedMail to prevent implicit 'any'
    let parsed: ParsedMail;
    try {
      parsed = await simpleParser(rawEml);
    } catch (_err) {
      // Biome Fix: Prefix unused error with underscore
      console.warn(`[Analyzer] Failed to parse EML: ${filePath}`);
      return null;
    }

    let messageId = (parsed.messageId || "").replace(/[<>]/g, "").trim();
    if (!messageId && parsed.headers.has("message-id")) {
      messageId = String(parsed.headers.get("message-id"))
        .replace(/[<>]/g, "")
        .trim();
    }

    const subject = parsed.subject || "no-subject";
    const senderRaw = parsed.from?.text || "unknown";
    const bodyRaw = parsed.text || "";

    // Deduplication is scoped to THIS case/request, not global. Each DSAR
    // request is an independent deliverable, so the same email involving two
    // custodians must be kept for BOTH requests. Folding the request scope
    // (cleanRelativePath) into the hash means different requests never collide,
    // while multiple PST files within the same request still dedup together.
    let baseHash: string;
    if (messageId && messageId.length > 5) {
      baseHash = crypto.createHash("sha256").update(messageId).digest("hex");
    } else {
      baseHash = generateFallbackHash(senderRaw, subject, bodyRaw);
    }
    const emailHash = crypto
      .createHash("sha256")
      .update(`${cleanRelativePath}::${baseHash}`)
      .digest("hex");

    const existingRecord = (await withSqliteBusyRetry(
      () => checkStmt.get(emailHash) as { id: string } | undefined,
      "check existing hash",
    )) as { id: string } | undefined;
    const isDuplicate = existingRecord ? 1 : 0;

    if (isDuplicate === 1) {
      metrics.duplicateCount++;
      fs.unlinkSync(filePath); // Destroy the duplicate file instantly to free disk space!
      return null; // Skip attachment parsing for duplicates
    }

    // Pre-filter: Rule 1 — discard privileged/confidential subjects immediately after dedup
    if (PRIVILEGED_KEYWORDS_RE.test(subject)) {
      const emailId = crypto.randomUUID();
      const sentDate = parsed.date ? parsed.date.toISOString() : "no-date";
      await withSqliteBusyRetry(
        () =>
          insertStmt.run(
            emailId,
            fileId,
            messageId,
            sentDate,
            emailHash,
            0,
            parentHash,
            parentHash ? 1 : 0,
          ),
        "insert pre-filter discard email",
      );
      await withSqliteBusyRetry(
        () =>
          db
            .prepare(
              "UPDATE emails SET ai_decision = 'discard', ai_reason = 'Pre-filter: Subject contains privileged/confidential keyword' WHERE id = ?",
            )
            .run(emailId),
        "mark pre-filter discard",
      );
      await withSqliteBusyRetry(
        () =>
          db
            .prepare(
              "UPDATE processed_files SET ai_discarded_count = ai_discarded_count + 1 WHERE id = ?",
            )
            .run(fileId),
        "increment discarded count",
      );
      metrics.uniqueCount++;
      fs.unlinkSync(filePath);
      return emailHash;
    }

    metrics.uniqueCount++;
    const emailId = crypto.randomUUID();
    const sentDate = parsed.date ? parsed.date.toISOString() : "no-date";

    // Move the unique EML to the secure .raw_fileId folder
    const finalEmlPath = path.join(targetFolder, `${emailId}.eml`);
    fs.copyFileSync(filePath, finalEmlPath);
    fs.unlinkSync(filePath); // Cleanup temp file

    // Insert into DB with relational logic (is it an attachment? does it have a parent?)
    await withSqliteBusyRetry(
      () =>
        insertStmt.run(
          emailId,
          fileId,
          messageId,
          sentDate,
          emailHash,
          0,
          parentHash,
          parentHash ? 1 : 0,
        ),
      "insert unique email",
    );

    // --- RECURSIVE ATTACHMENT FLATTENING ---
    if (parsed.attachments && parsed.attachments.length > 0) {
      metrics.totalAttachments += parsed.attachments.length;

      for (const att of parsed.attachments) {
        const mimeType = (att.contentType || "").toLowerCase();
        const ext = path.extname(att.filename || "").toLowerCase();

        // If it's a nested email, extract it to a flat file and parse recursively
        if (mimeType === "message/rfc822" || ext === ".eml" || ext === ".msg") {
          const nestedFileName = `nested_${crypto.randomUUID()}${ext || ".eml"}`;
          const nestedTempPath = path.join(tempDir, nestedFileName);

          const contentBuf = Buffer.isBuffer(att.content)
            ? att.content
            : Buffer.from(att.content);
          fs.writeFileSync(nestedTempPath, contentBuf);

          if (ext !== ".msg") {
            await processEmlFile(nestedTempPath, emailHash);
          } else {
            await processMsgFile(nestedTempPath, emailHash);
          }
        }
      }
    }

    return emailHash;
  }

  // Start the Walker on all top-level EMLs created by readpst
  for (const file of emlFiles) {
    if (fs.existsSync(file)) {
      await processEmlFile(file, null);
    }
  }

  // ==========================================
  // PHASE 3: Cleanup & Finalize
  // ==========================================
  if (fs.existsSync(tempDir)) {
    fs.rmSync(tempDir, { recursive: true, force: true });
  }

  await withSqliteBusyRetry(
    () =>
      db
        .prepare(`
    UPDATE processed_files 
    SET status = 'analyzed', total_emails = ?, unique_emails = ?, duplicate_emails = ?, total_attachments = ?
    WHERE id = ?
  `)
        .run(
          metrics.totalProcessed,
          metrics.uniqueCount,
          metrics.duplicateCount,
          metrics.totalAttachments,
          fileId,
        ),
    "finalize analyzed metrics",
  );

  console.log(
    `[Analyzer] Parse & dedup complete for ${fileId}. Unique: ${metrics.uniqueCount}, Duplicates: ${metrics.duplicateCount}. (Next phases: extract, AI, render.)`,
  );
  return metrics;
}
