import { spawn } from "node:child_process";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { type ParsedMail, simpleParser } from "mailparser";
import { db } from "./db";

interface AnalysisMetrics {
  uniqueCount: number;
  duplicateCount: number;
  totalProcessed: number;
  totalAttachments: number;
}

// Smarter Fallback Generator for emails without standard Message-IDs
function generateFallbackHash(
  senderRaw: string,
  subjectRaw: string,
  bodyRaw: string,
): string {
  const sender = (senderRaw || "").toLowerCase().replace(/[^a-z0-9]/g, "");
  const subject = (subjectRaw || "")
    .toLowerCase()
    .replace(/^(re|fw|fwd|wg|aw)\s*:\s*/g, "")
    .replace(/[^a-z0-9]/g, "");
  const body = (bodyRaw || "")
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "")
    .substring(20, 120);

  return crypto
    .createHash("sha256")
    .update(`${sender}_${subject}_${body}`)
    .digest("hex");
}

export async function scanFileMetadata(fileId: string): Promise<void> {
  // 🚀 ARCHITECTURE UPGRADE:
  // readpst does not support scanning without extracting.
  // We instantly advance the file to pending_analysis so the UI orchestrator moves directly to Phase 2.
  db.prepare(`
    UPDATE processed_files 
    SET total_emails = 0, total_attachments = 0, status = 'pending_analysis'
    WHERE id = ?
  `).run(fileId);
}

// Helper to recursively collect all EMLs generated by readpst
async function getEmlFiles(
  dir: string,
  fileList: string[] = [],
): Promise<string[]> {
  if (!fs.existsSync(dir)) return fileList;
  const files = await fs.promises.readdir(dir, { withFileTypes: true });
  for (const file of files) {
    const fullPath = path.join(dir, file.name);
    if (file.isDirectory()) {
      await getEmlFiles(fullPath, fileList);
    } else if (file.name.toLowerCase().endsWith(".eml")) {
      fileList.push(fullPath);
    }
  }
  return fileList;
}

export async function analyzePstDuplicates(
  fileId: string,
  outputBaseDir = process.env.EXTRACTED_PATH ||
    "/Users/rgomes/Projects/extracted_emails",
) {
  const row = db
    .prepare("SELECT filepath FROM processed_files WHERE id = ?")
    .get(fileId) as { filepath: string } | undefined;
  if (!row) throw new Error("File metadata not found.");

  db.prepare(
    "UPDATE processed_files SET status = 'processing' WHERE id = ?",
  ).run(fileId);
  db.prepare("DELETE FROM emails WHERE file_id = ?").run(fileId);

  const stagingPath =
    process.env.STAGING_PATH || "/Users/rgomes/Projects/staging-area";

  let cleanRelativePath = "";
  if (row.filepath.startsWith(stagingPath)) {
    const rel = path.relative(stagingPath, row.filepath);
    cleanRelativePath = path.dirname(rel);
  } else {
    cleanRelativePath = fileId;
  }

  if (cleanRelativePath === "." || cleanRelativePath === "") {
    cleanRelativePath = path.parse(row.filepath).name;
  }

  // The final destination for our perfectly extracted unique EMLs
  const targetFolder = path.join(
    outputBaseDir,
    cleanRelativePath,
    `.raw_${fileId}`,
  );
  if (!fs.existsSync(targetFolder))
    fs.mkdirSync(targetFolder, { recursive: true });

  // The temporary extraction sandbox
  const tempDir = path.join(outputBaseDir, `.tmp_extract_${fileId}`);
  if (fs.existsSync(tempDir))
    fs.rmSync(tempDir, { recursive: true, force: true });
  fs.mkdirSync(tempDir, { recursive: true });

  const metrics: AnalysisMetrics = {
    uniqueCount: 0,
    duplicateCount: 0,
    totalProcessed: 0,
    totalAttachments: 0,
  };

  // ==========================================
  // PHASE 1: Brute-Force Extraction (libpst)
  // ==========================================
  console.log(`[Analyzer] Spawning readpst for file ${fileId}...`);
  await new Promise<void>((resolve, reject) => {
    // -r = Recursive folder extraction, -e = Output as standard .eml, -o = Target directory
    const child = spawn("readpst", ["-r", "-e", "-o", tempDir, row.filepath]);

    child.on("error", (err) => {
      reject(
        new Error(
          `Failed to start readpst. Is libpst installed on the system? Error: ${err.message}`,
        ),
      );
    });

    child.on("close", (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`readpst failed with exit code ${code}`));
      }
    });
  });

  console.log(
    `[Analyzer] readpst complete. Scanning temp directory for EMLs...`,
  );

  // ==========================================
  // PHASE 2: Flatten & Deduplicate
  // ==========================================
  const emlFiles = await getEmlFiles(tempDir);

  const checkStmt = db.prepare(
    "SELECT id FROM emails WHERE email_hash = ? LIMIT 1",
  );
  const insertStmt = db.prepare(`
    INSERT INTO emails (id, file_id, message_id, sent_date, email_hash, is_duplicate, parent_email_hash, is_attachment)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
  `);

  async function processEmlFile(
    filePath: string,
    parentHash: string | null = null,
  ) {
    metrics.totalProcessed++;
    const rawEml = fs.readFileSync(filePath);

    // Biome Fix: Explicitly type as ParsedMail to prevent implicit 'any'
    let parsed: ParsedMail;
    try {
      parsed = await simpleParser(rawEml);
    } catch (_err) {
      // Biome Fix: Prefix unused error with underscore
      console.warn(`[Analyzer] Failed to parse EML: ${filePath}`);
      return;
    }

    let messageId = (parsed.messageId || "").replace(/[<>]/g, "").trim();
    if (!messageId && parsed.headers.has("message-id")) {
      messageId = String(parsed.headers.get("message-id"))
        .replace(/[<>]/g, "")
        .trim();
    }

    const subject = parsed.subject || "no-subject";
    const senderRaw = parsed.from?.text || "unknown";
    const bodyRaw = parsed.text || "";

    let emailHash: string;
    if (messageId && messageId.length > 5) {
      emailHash = crypto.createHash("sha256").update(messageId).digest("hex");
    } else {
      emailHash = generateFallbackHash(senderRaw, subject, bodyRaw);
    }

    const existingRecord = checkStmt.get(emailHash) as
      | { id: string }
      | undefined;
    const isDuplicate = existingRecord ? 1 : 0;

    if (isDuplicate === 1) {
      metrics.duplicateCount++;
      fs.unlinkSync(filePath); // Destroy the duplicate file instantly to free disk space!
      return; // Skip attachment parsing for duplicates
    }

    metrics.uniqueCount++;
    const emailId = crypto.randomUUID();
    const sentDate = parsed.date ? parsed.date.toISOString() : "no-date";

    // Move the unique EML to the secure .raw_fileId folder
    const finalEmlPath = path.join(targetFolder, `${emailId}.eml`);
    fs.copyFileSync(filePath, finalEmlPath);
    fs.unlinkSync(filePath); // Cleanup temp file

    // Insert into DB with relational logic (is it an attachment? does it have a parent?)
    insertStmt.run(
      emailId,
      fileId,
      messageId,
      sentDate,
      emailHash,
      0,
      parentHash,
      parentHash ? 1 : 0,
    );

    // --- RECURSIVE ATTACHMENT FLATTENING ---
    if (parsed.attachments && parsed.attachments.length > 0) {
      metrics.totalAttachments += parsed.attachments.length;

      for (const att of parsed.attachments) {
        const mimeType = (att.contentType || "").toLowerCase();
        const ext = path.extname(att.filename || "").toLowerCase();

        // If it's a nested email, extract it to a flat file and parse recursively
        if (mimeType === "message/rfc822" || ext === ".eml" || ext === ".msg") {
          const nestedFileName = `nested_${crypto.randomUUID()}${ext || ".eml"}`;
          const nestedTempPath = path.join(tempDir, nestedFileName);

          const contentBuf = Buffer.isBuffer(att.content)
            ? att.content
            : Buffer.from(att.content);
          fs.writeFileSync(nestedTempPath, contentBuf);

          // Note: MSG files require `@kenjiuno/msgreader`. For now, `readpst` usually converts them to EML.
          if (ext !== ".msg") {
            await processEmlFile(nestedTempPath, emailHash);
          } else {
            console.log(
              `[Analyzer] Warning: MSG attachment detected. You will need msgreader installed to crack this open on Linux/Mac.`,
            );
          }
        }
      }
    }
  }

  // Start the Walker on all top-level EMLs created by readpst
  for (const file of emlFiles) {
    if (fs.existsSync(file)) {
      await processEmlFile(file, null);
    }
  }

  // ==========================================
  // PHASE 3: Cleanup & Finalize
  // ==========================================
  if (fs.existsSync(tempDir)) {
    fs.rmSync(tempDir, { recursive: true, force: true });
  }

  db.prepare(`
    UPDATE processed_files 
    SET status = 'analyzed', total_emails = ?, unique_emails = ?, duplicate_emails = ?, total_attachments = ?
    WHERE id = ?
  `).run(
    metrics.totalProcessed,
    metrics.uniqueCount,
    metrics.duplicateCount,
    metrics.totalAttachments,
    fileId,
  );

  console.log(
    `[Analyzer] Case ${fileId} complete! Unique: ${metrics.uniqueCount}, Duplicates: ${metrics.duplicateCount}`,
  );
  return metrics;
}
