import { spawn } from "node:child_process";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import type { FieldsData } from "@kenjiuno/msgreader";
import MsgReader from "@kenjiuno/msgreader";
import { type ParsedMail, simpleParser } from "mailparser";
import { PRIVILEGED_KEYWORDS_RE } from "./exclusions";
import { prisma } from "./prisma";
import { getPstArtifactPaths } from "./pst-artifacts";

interface AnalysisMetrics {
  uniqueCount: number;
  duplicateCount: number;
  totalProcessed: number;
  totalAttachments: number;
}

// Smarter Fallback Generator for emails without standard Message-IDs
function generateFallbackHash(
  senderRaw: string,
  subjectRaw: string,
  bodyRaw: string,
): string {
  const sender = (senderRaw || "").toLowerCase().replace(/[^a-z0-9]/g, "");
  const subject = (subjectRaw || "")
    .toLowerCase()
    .replace(/^(re|fw|fwd|wg|aw)\s*:\s*/g, "")
    .replace(/[^a-z0-9]/g, "");
  const body = (bodyRaw || "")
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "")
    .substring(20, 120);

  return crypto
    .createHash("sha256")
    .update(`${sender}_${subject}_${body}`)
    .digest("hex");
}

export async function scanFileMetadata(fileId: string): Promise<void> {
  // 🚀 ARCHITECTURE UPGRADE:
  // readpst does not support scanning without extracting.
  // We instantly advance the file to pending_analysis so the UI orchestrator moves directly to Phase 2.
  await prisma.processedFile.update({
    where: { id: fileId },
    data: { total_emails: 0, total_attachments: 0, status: "pending_analysis" },
  });
}

// Helper to recursively collect all EMLs generated by readpst
async function getEmlFiles(
  dir: string,
  fileList: string[] = [],
): Promise<string[]> {
  if (!fs.existsSync(dir)) return fileList;
  const files = await fs.promises.readdir(dir, { withFileTypes: true });
  for (const file of files) {
    const fullPath = path.join(dir, file.name);
    if (file.isDirectory()) {
      await getEmlFiles(fullPath, fileList);
    } else if (file.name.toLowerCase().endsWith(".eml")) {
      fileList.push(fullPath);
    }
  }
  return fileList;
}

export async function analyzePstDuplicates(
  fileId: string,
  outputBaseDir = process.env.EXTRACTED_PATH ||
    "/Users/rgomes/Projects/extracted_emails",
) {
  const row = await prisma.processedFile.findUnique({
    where: { id: fileId },
    select: {
      filepath: true,
      subject_email: true,
      subject_personal_email: true,
    },
  });
  if (!row?.filepath) throw new Error("File metadata not found.");
  const filepath = row.filepath;

  // subjectEmail  = personal email: emails TO this address bypass the keyword pre-filter.
  // subjectCompanyEmail = work email: emails FROM this TO the personal email are self-forwards
  //   and are routed to Emails/Warning/ by the converter.
  const subjectEmail = (row.subject_personal_email || "").trim().toLowerCase();
  const subjectCompanyEmail = (row.subject_email || "").trim().toLowerCase();

  await prisma.processedFile.update({
    where: { id: fileId },
    data: {
      status: "processing",
      // Parse retries rebuild the email rows, so their derived counters must
      // start fresh rather than accumulating decisions from an interrupted run.
      ai_approved_count: 0,
      ai_discarded_count: 0,
    },
  });
  await prisma.email.deleteMany({ where: { file_id: fileId } });

  const stagingPath =
    process.env.STAGING_PATH || "/Users/rgomes/Projects/staging-area";

  const {
    caseFolder,
    rawEmlFolder: targetFolder,
    sourceRelativePath: cleanRelativePath,
  } = getPstArtifactPaths({
    fileId,
    filepath,
    stagingPath,
    extractedPath: outputBaseDir,
  });
  if (!fs.existsSync(caseFolder)) fs.mkdirSync(caseFolder, { recursive: true });

  // A retry must never reuse a partial Parse artifact left by a killed worker.
  if (fs.existsSync(targetFolder)) {
    fs.rmSync(targetFolder, { recursive: true, force: true });
  }
  fs.mkdirSync(targetFolder, { recursive: true });

  // The temporary extraction sandbox
  const tempDir = path.join(outputBaseDir, `.tmp_extract_${fileId}`);
  if (fs.existsSync(tempDir))
    fs.rmSync(tempDir, { recursive: true, force: true });
  fs.mkdirSync(tempDir, { recursive: true });

  const metrics: AnalysisMetrics = {
    uniqueCount: 0,
    duplicateCount: 0,
    totalProcessed: 0,
    totalAttachments: 0,
  };

  // ==========================================
  // PHASE 1: Brute-Force Extraction (libpst)
  // ==========================================
  // Fail fast with a clear message if the source PST no longer exists on disk
  // (e.g. a stale DB row left behind after the staging layout was reorganized).
  if (!fs.existsSync(filepath)) {
    throw new Error(
      `Source PST not found on disk: ${filepath}. The staging file was likely moved or deleted, leaving a stale record. Re-sync the staging area (and reset/remove this case) before retrying.`,
    );
  }

  console.log(`[Analyzer] Spawning readpst for file ${fileId}...`);
  await new Promise<void>((resolve, reject) => {
    // -r = Recursive folder extraction, -e = Output as standard .eml, -o = Target directory
    const child = spawn("readpst", ["-r", "-e", "-o", tempDir, filepath]);

    let stderr = "";
    child.stderr?.on("data", (chunk) => {
      stderr += chunk.toString();
    });

    child.on("error", (err) => {
      reject(
        new Error(
          `Failed to start readpst. Is libpst installed on the system? Error: ${err.message}`,
        ),
      );
    });

    child.on("close", (code) => {
      if (code === 0) {
        resolve();
      } else {
        const detail = stderr.trim();
        reject(
          new Error(
            `readpst failed with exit code ${code} for ${filepath}${
              detail ? `: ${detail}` : ""
            }`,
          ),
        );
      }
    });
  });

  console.log(
    `[Analyzer] readpst complete. Scanning temp directory for EMLs...`,
  );

  // ==========================================
  // PHASE 2: Flatten & Deduplicate
  // ==========================================
  const emlFiles = await getEmlFiles(tempDir);

  function msgDataToEml(data: {
    headers?: string;
    senderEmail?: string;
    senderName?: string;
    recipients?: Array<{ email?: string; name?: string }>;
    subject?: string;
    messageDeliveryTime?: string;
    clientSubmitTime?: string;
    creationTime?: string;
    body?: string;
  }): string {
    const normalizedHeaders = (data.headers || "").trim();
    if (
      /^from:/im.test(normalizedHeaders) &&
      /^subject:/im.test(normalizedHeaders)
    ) {
      return `${normalizedHeaders}\n\n${data.body || ""}`;
    }

    const sender =
      data.senderEmail || data.senderName || "unknown@example.invalid";
    const recipients = (data.recipients || [])
      .map((r) => r.email || r.name || "")
      .filter(Boolean)
      .join(", ");
    const sentAt =
      data.messageDeliveryTime || data.clientSubmitTime || data.creationTime;

    const lines = [
      `From: ${sender}`,
      `To: ${recipients || "undisclosed-recipients:;"}`,
      `Subject: ${data.subject || "(no subject)"}`,
      ...(sentAt ? [`Date: ${sentAt}`] : []),
      "MIME-Version: 1.0",
      'Content-Type: text/plain; charset="utf-8"',
      "",
      data.body || "",
    ];

    return lines.join("\n");
  }

  async function processMsgFile(
    msgPath: string,
    parentHash: string | null = null,
  ): Promise<void> {
    try {
      const msgBuffer = fs.readFileSync(msgPath);
      const reader = new MsgReader(
        new DataView(
          msgBuffer.buffer,
          msgBuffer.byteOffset,
          msgBuffer.byteLength,
        ),
      );
      const msgData = reader.getFileData() as {
        headers?: string;
        senderEmail?: string;
        senderName?: string;
        recipients?: Array<{ email?: string; name?: string }>;
        subject?: string;
        messageDeliveryTime?: string;
        clientSubmitTime?: string;
        creationTime?: string;
        body?: string;
        attachments?: FieldsData[];
      };

      const synthesizedEmlPath = path.join(
        tempDir,
        `msg_${crypto.randomUUID()}.eml`,
      );
      fs.writeFileSync(synthesizedEmlPath, msgDataToEml(msgData));

      const msgEmailHash = await processEmlFile(synthesizedEmlPath, parentHash);
      const nestedParentHash = msgEmailHash || parentHash;

      if (!msgData.attachments || msgData.attachments.length === 0) return;

      metrics.totalAttachments += msgData.attachments.length;

      for (const msgAttachment of msgData.attachments) {
        let extracted:
          | { fileName?: string; content?: Uint8Array | Buffer | string }
          | undefined;

        try {
          extracted = reader.getAttachment(msgAttachment) as {
            fileName?: string;
            content?: Uint8Array | Buffer | string;
          };
        } catch (_err) {
          continue;
        }

        const content = extracted?.content;
        if (!content) continue;

        const attachmentName =
          extracted?.fileName ||
          msgAttachment.fileName ||
          msgAttachment.fileNameShort ||
          `msg_att_${crypto.randomUUID()}`;
        const attachmentExt = path.extname(attachmentName).toLowerCase();
        if (attachmentExt !== ".eml" && attachmentExt !== ".msg") continue;

        const nestedTempPath = path.join(
          tempDir,
          `nested_${crypto.randomUUID()}${attachmentExt}`,
        );

        const nestedBuffer = Buffer.isBuffer(content)
          ? content
          : typeof content === "string"
            ? Buffer.from(content)
            : Buffer.from(content);

        fs.writeFileSync(nestedTempPath, nestedBuffer);

        if (attachmentExt === ".msg") {
          await processMsgFile(nestedTempPath, nestedParentHash);
        } else {
          await processEmlFile(nestedTempPath, nestedParentHash);
        }
      }
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      console.warn(
        `[Analyzer] Failed to parse MSG file ${msgPath}: ${message}`,
      );
    }
  }

  async function processEmlFile(
    filePath: string,
    parentHash: string | null = null,
  ): Promise<string | null> {
    metrics.totalProcessed++;
    const rawEml = fs.readFileSync(filePath);

    // Biome Fix: Explicitly type as ParsedMail to prevent implicit 'any'
    let parsed: ParsedMail;
    try {
      parsed = await simpleParser(rawEml);
    } catch (_err) {
      // Biome Fix: Prefix unused error with underscore
      console.warn(`[Analyzer] Failed to parse EML: ${filePath}`);
      return null;
    }

    let messageId = (parsed.messageId || "").replace(/[<>]/g, "").trim();
    if (!messageId && parsed.headers.has("message-id")) {
      messageId = String(parsed.headers.get("message-id"))
        .replace(/[<>]/g, "")
        .trim();
    }

    const subject = parsed.subject || "no-subject";
    const senderRaw = parsed.from?.text || "unknown";
    const bodyRaw = parsed.text || "";

    // Deduplication is scoped to THIS case/request, not global. Each DSAR
    // request is an independent deliverable, so the same email involving two
    // custodians must be kept for BOTH requests. Folding the request scope
    // (cleanRelativePath) into the hash means different requests never collide,
    // while multiple PST files within the same request still dedup together.
    let baseHash: string;
    if (messageId && messageId.length > 5) {
      baseHash = crypto.createHash("sha256").update(messageId).digest("hex");
    } else {
      baseHash = generateFallbackHash(senderRaw, subject, bodyRaw);
    }
    const emailHash = crypto
      .createHash("sha256")
      .update(`${cleanRelativePath}::${baseHash}`)
      .digest("hex");

    const existingRecord = await prisma.email.findFirst({
      where: { email_hash: emailHash },
      select: { id: true },
    });
    const isDuplicate = existingRecord ? 1 : 0;

    if (isDuplicate === 1) {
      metrics.duplicateCount++;
      fs.unlinkSync(filePath); // Destroy the duplicate file instantly to free disk space!
      return null; // Skip attachment parsing for duplicates
    }

    // Pre-filter: Rule 1 — discard privileged/confidential subjects immediately after dedup.
    // Exception: if the email was sent directly TO the subject's personal email address,
    // include it regardless of privileged keywords — it is personally relevant to the subject.
    const collectAddresses = (
      value: ParsedMail["to"] | ParsedMail["from"],
    ): string[] => {
      if (!value) return [];
      const containers = Array.isArray(value) ? value : [value];
      return containers
        .flatMap((container) => container.value ?? [])
        .map((entry) => (entry.address ?? "").toLowerCase())
        .filter(Boolean);
    };

    const toAddresses = collectAddresses(parsed.to);
    const sentToSubjectEmail =
      subjectEmail.length > 0 && toAddresses.includes(subjectEmail);

    // Self-forward detection: subject sending from company email to personal email.
    const fromAddresses = collectAddresses(parsed.from);
    const isSelfForward =
      subjectCompanyEmail.length > 0 &&
      subjectEmail.length > 0 &&
      fromAddresses.includes(subjectCompanyEmail) &&
      toAddresses.includes(subjectEmail);

    if (PRIVILEGED_KEYWORDS_RE.test(subject) && !sentToSubjectEmail) {
      const emailId = crypto.randomUUID();
      const sentDate = parsed.date ? parsed.date.toISOString() : "no-date";
      await prisma.email.create({
        data: {
          id: emailId,
          file_id: fileId,
          message_id: messageId,
          sent_date: sentDate,
          email_hash: emailHash,
          is_duplicate: 0,
          parent_email_hash: parentHash,
          is_attachment: parentHash ? 1 : 0,
          ai_decision: "discard",
          ai_reason:
            "Pre-filter: Subject contains privileged/confidential keyword",
        },
      });
      await prisma.processedFile.update({
        where: { id: fileId },
        data: { ai_discarded_count: { increment: 1 } },
      });
      metrics.uniqueCount++;
      fs.unlinkSync(filePath);
      return emailHash;
    }

    metrics.uniqueCount++;
    const emailId = crypto.randomUUID();
    const sentDate = parsed.date ? parsed.date.toISOString() : "no-date";

    // Move the unique EML to the secure .raw_fileId folder
    const finalEmlPath = path.join(targetFolder, `${emailId}.eml`);
    fs.copyFileSync(filePath, finalEmlPath);
    fs.unlinkSync(filePath); // Cleanup temp file

    // Insert into DB with relational logic (is it an attachment? does it have a parent?)
    await prisma.email.create({
      data: {
        id: emailId,
        file_id: fileId,
        message_id: messageId,
        sent_date: sentDate,
        email_hash: emailHash,
        is_duplicate: 0,
        parent_email_hash: parentHash,
        is_attachment: parentHash ? 1 : 0,
        ...(isSelfForward
          ? {
              ai_decision: "warning",
              ai_reason:
                "Self-forward: Subject sent from company email to personal email",
            }
          : {}),
      },
    });

    // --- RECURSIVE ATTACHMENT FLATTENING ---
    if (parsed.attachments && parsed.attachments.length > 0) {
      metrics.totalAttachments += parsed.attachments.length;

      for (const att of parsed.attachments) {
        const mimeType = (att.contentType || "").toLowerCase();
        const ext = path.extname(att.filename || "").toLowerCase();

        // If it's a nested email, extract it to a flat file and parse recursively
        if (mimeType === "message/rfc822" || ext === ".eml" || ext === ".msg") {
          const nestedFileName = `nested_${crypto.randomUUID()}${ext || ".eml"}`;
          const nestedTempPath = path.join(tempDir, nestedFileName);

          const contentBuf = Buffer.isBuffer(att.content)
            ? att.content
            : Buffer.from(att.content);
          fs.writeFileSync(nestedTempPath, contentBuf);

          if (ext !== ".msg") {
            await processEmlFile(nestedTempPath, emailHash);
          } else {
            await processMsgFile(nestedTempPath, emailHash);
          }
        }
      }
    }

    return emailHash;
  }

  // Start the Walker on all top-level EMLs created by readpst.
  // Large PSTs can take a long time here, so emit heartbeat logs.
  const topLevelTotal = emlFiles.length;
  for (let i = 0; i < topLevelTotal; i++) {
    const file = emlFiles[i];
    if (!fs.existsSync(file)) continue;

    await processEmlFile(file, null);

    if ((i + 1) % 200 === 0 || i + 1 === topLevelTotal) {
      console.log(
        `[Analyzer] Top-level progress for ${fileId}: ${i + 1}/${topLevelTotal} files scanned (emails parsed: ${metrics.totalProcessed}).`,
      );
    }
  }

  // ==========================================
  // PHASE 3: Cleanup & Finalize
  // ==========================================
  if (fs.existsSync(tempDir)) {
    fs.rmSync(tempDir, { recursive: true, force: true });
  }

  await prisma.processedFile.update({
    where: { id: fileId },
    data: {
      status: "analyzed",
      total_emails: metrics.totalProcessed,
      unique_emails: metrics.uniqueCount,
      duplicate_emails: metrics.duplicateCount,
      total_attachments: metrics.totalAttachments,
    },
  });

  console.log(
    `[Analyzer] Parse & dedup complete for ${fileId}. Unique: ${metrics.uniqueCount}, Duplicates: ${metrics.duplicateCount}. (Next phases: extract, AI, render.)`,
  );
  return metrics;
}
