ALTER TABLE "processed_files"
  ADD COLUMN IF NOT EXISTS "upload_status" TEXT NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS "upload_total" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "upload_uploaded" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "upload_error" TEXT;
